# 라이브러리 설치

In [2]:
!pip install numpy

In [3]:
import numpy as np

print(np.__version__)

2.1.1


In [5]:
#help(np)

In [6]:
num1 = [1, 2, 3]
num2 = [4, 5, 6]
# 569
num1+num2

[1, 2, 3, 4, 5, 6]

In [10]:
num1_arr = np.array(num1)
num2_arr = np.array(num2)
num1_arr+num2_arr

array([5, 7, 9])

In [14]:
print(type(num1_arr))

<class 'numpy.ndarray'>


In [16]:
num1_arr.T

array([1, 2, 3])

In [17]:
num1_arr.data

In [18]:
num1_arr.dtype # 해당되는 배열의 데이터 타입을 출력

dtype('int64')

In [20]:
num1_arr.shape #주로씀

(3,)

In [21]:
num1_arr.ndim

1

In [22]:
num1_arr.max()

np.int64(3)

# 우리 회사에서 주로 다루는 데이터는 0원 ~ 백만원 미만
0~1000000

In [24]:
num1_arr = np.array(num1, dtype = "int8")
num1_arr.dtype

dtype('int8')

# 배열만드는 방법

In [26]:
# 기본적으로 다른 데이터 자료형으로 numpy 배열로 변환
# 배열 생성
print(np.ones(3))

[1. 1. 1.]


In [31]:
import numpy as np
print(np.zeros(3))

[0. 0. 0.]


In [38]:
arr=np.ndarray(shape=(3, 3), dtype = float, order = 'f')
# shape안에 콤마 만큼 차원이 늘어남 지금은 2차원
arr.shape

(3, 3)

# 배열의 차원변경

In [44]:
temp_arr = np.arange(16)
temp_arr.reshape(2,2,4)  # 배열의 차원 변경 안에거를 곱해서 16만 나오면 됨

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
temp_arr = np.arange(16)
temp_arr.reshape(2,2,4)

In [45]:
a16 = np.array([1.333333],dtype = np.float16)
a32 = np.array([1.333333],dtype = np.float32)
print(a16)
print(a32)   
# 두 결과는 전혀 다른값인 거고 무슨 비트로 받아서 처리할지 고려해야한다

[1.333]
[1.333333]


In [46]:
arr = np.array([-1, 2, -3])
arr/0

C:\Users\campus3S012\AppData\Local\Temp\ipykernel_8024\510923086.py:2: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([-inf,  inf, -inf])

결측치
- missing values : 잃어버린 값
- nan : not a number, --> 아직 정의되지 않은 숫자 의미

In [47]:
print(np.nan, type(np.nan))

nan <class 'float'>


In [48]:
print(np.inf, type(np.inf))   # inf는 무한대

inf <class 'float'>


In [50]:
print(-np.inf, type(-np.inf)) # 애네들이 정의한거니 그렇게 알기

-inf <class 'float'>


In [52]:
arr=np.array([-1,2,-3])
print(arr + np.nan)
print(arr + np.inf)

[nan nan nan]
[inf inf inf]


# 인덱싱 & 슬라이싱

In [55]:
arr = np.arange(10)
arr[1:5]

array([1, 2, 3, 4])

In [59]:
arr = np.arange(10).reshape(2, 5)
arr[0][2]

np.int64(2)

In [78]:
arr = np.arange(10000).reshape(100, 100)
arr[0:2][0:5]   #[시작:최대 두블럭], [시작하는 블럭 순서:몇개까지 블럭 나오게할건지]

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
        152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
        165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 17

In [79]:
arr = np.arange(4)
arr[:2]

array([0, 1])

In [104]:
# arr[행:열
arr = np.arange(20).reshape(4,5)
arr[1:4,2:5] # arr[행:열]   arr[1: 끝까지 쓸거면 안써도됨]  arr[1:4,2:5] or arr[1:4]/arr[1:2:]      1:4,2:5 에서 2는 2열부터 5는 5행까지     [시작: 끝, 어디부터 시작할지:어디까지할지]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

# 브로드캐스팅 연산

In [106]:
a = np.array([1,2,3])
b = np.array([1,2,3])
a+b

array([2, 4, 6])

In [107]:
a = np.array([1,2,3]) 
b=3.0  # 3.0의 값을 갖고 있는 1차 배열이 만들어져서 하나씩 더해졌다고 생각하면 됨
a+b #각각 3.0을 더함

array([4., 5., 6.])

## 문제 1. 
문제: 모든 값이 0으로 2차원 배열 (5, 5) 만드세요. 

In [116]:
import numpy as np
a= np.zeros(25).reshape(5,5)
a


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## 문제 2. 
임의의 3x3 크기의 배열을 생성하고 배열의 shape(모양), dtype(데이터 타입), 그리고 배열의 차원 수(ndim)를 출력하세요.

In [137]:
a= np.arange(9).reshape(3,3)
print(a)
print(a.shape)
print(a.dtype)
print(a.ndim)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
int64
2


## 문제 3. 
- 주어진 배열에서 아래와 같이 슬라이싱 하세요. 
```
array([[ 5,  6],
       [ 9, 10]])
```

In [148]:
arr = np.arange(16).reshape(4,4)
print (arr)
arr[1:3,1:3]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 5,  6],
       [ 9, 10]])

# 조건 연산
-원하는 결과값 : true/false

In [149]:
arr=np.array([10,20,30])
arr>10

array([False,  True,  True])

In [150]:
arr=np.array([10,20,30])
cond = [False,  True,  True]

arr[cond] #트루 값만 가져온다

array([20, 30])

In [151]:
arr=np.array([18,20, 50, 30, 16])
cond = arr > 18
arr[cond] #트루값만 가져오니 필터처리한것다다

array([20, 50, 30])

In [153]:
arr=np.array([18,20, 50, 30, 16])
arr[arr > 18]


array([20, 50, 30])

In [155]:
arr=np.array([18,20, 50, 30, 16,65,70])
cond0 = arr > 18
cond1 = arr < 65

arr[cond0 & cond1]

array([20, 50, 30])

In [156]:
arr[cond0 | cond1]

array([18, 20, 50, 30, 16, 65, 70])

In [160]:
# 권장사항 이유 판다스 : 다중조건 필터링할때는 아래방법으로만 가능
# 반드시 ()가 필요
arr[(cond0 | cond1)]

array([18, 20, 50, 30, 16, 65, 70])

## np.where

In [163]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

## 함수와 메서드

In [169]:
arr= np.arange(8).reshape(4,2)
print(arr)
arr.sum()

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


np.int64(28)

In [167]:
arr.sum(axis=0) #x축 방향으로 행단위의 데이터의 합을 구하라

array([12, 16])

In [170]:
arr.sum(axis = 1) # y축 방향으로 열단위의 데이터의 합을 구하라

array([ 1,  5,  9, 13])

In [196]:
#무작위 랜덤 함수 만들기
np.random.seed(42) #나중에 머신러닝에서 씀 이거 쓰면 랜덤값이 안바뀜
np.random.randint(10)

6

In [202]:
np.random.randint(46, size =(3, 4)) # 46의미하는 것은 0~45번째까지중에 무작위로 가져오겠다는 뜻


array([[43, 29, 37,  1],
       [20, 32, 11, 21],
       [43, 24, 26, 41]], dtype=int32)

In [205]:
x= np.linspace(0,100,11) # linspace(시작값,종료값,균일값)는 균일하게 나누는거
print(x)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [1]:
import pandas as pd
pd.__version__ 

'2.2.3'

In [2]:
data = [10, 20, 30]
s = pd.Series(data)
s

0    10
1    20
2    30
dtype: int64

In [3]:
print(type(s))

<class 'pandas.core.series.Series'>


In [4]:
import numpy as np
data = np.arange(5)
s = pd.Series(data)
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [6]:
import numpy as np
data = np.arange(5)
s = pd.DataFrame(data)
s

0
0  0
1  1
2  2
3  3
4  4

In [7]:
data = ["tlrk","rhrk"]
s=pd.Series(data)
s

0    tlrk
1    rhrk
dtype: object

In [11]:
data = ["80000","90000"]
s=pd.Series(data)
s

0    80000
1    90000
dtype: object

## 시리즈 인덱스

In [16]:
data = [1000,2000,3000]
s =pd.Series(data)
print(s.index, type(s.index))

RangeIndex(start=0, stop=3, step=1) <class 'pandas.core.indexes.range.RangeIndex'>


In [17]:
list(s.index) # 형변환 시킨것

[0, 1, 2]

In [18]:
s.index.to_list()


[0, 1, 2]

In [19]:
help(s.index) #클래스에는 항상 속성과 메서드가 존재한다.

Help on RangeIndex in module pandas.core.indexes.range object:

class RangeIndex(pandas.core.indexes.base.Index)
 |  RangeIndex(start=None, stop=None, step=None, dtype: 'Dtype | None' = None, copy: 'bool' = False, name: 'Hashable | None' = None) -> 'Self'
 |
 |  Immutable Index implementing a monotonic integer range.
 |
 |  RangeIndex is a memory-saving special case of an Index limited to representing
 |  monotonic ranges with a 64-bit dtype. Using RangeIndex may in some instances
 |  improve computing speed.
 |
 |  This is the default index type used
 |  by DataFrame and Series when no explicit index is provided by the user.
 |
 |  Parameters
 |  ----------
 |  start : int (default: 0), range, or other RangeIndex instance
 |      If int and "stop" is not given, interpreted as "stop" instead.
 |  stop : int (default: 0)
 |  step : int (default: 1)
 |  dtype : np.int64
 |      Unused, accepted for homogeneity with other index types.
 |  copy : bool, default False
 |      Unused, accepte

In [36]:
# 시리즈 생성하면서 인덱스도 같이 생성
data = [1000,2000,3000]
index=["메로나","월드콘","와"]
s = pd.Series(data,index)
s

메로나    1000
월드콘    2000
와      3000
dtype: int64

In [37]:
s.values,type(s.values)

(array([1000, 2000, 3000]), numpy.ndarray)

## 시리즈 인덱싱

In [38]:
print(s.iloc[1])

2000


In [39]:
print(s.loc['메로나'])

1000


In [40]:
data = [1000,2000,3000]
#인덱스가 없음
s2 = pd.Series(data=data)
print(s2.iloc[0])
print(s2.loc['메로나']) # loc는 값으로 처리를 하는거고 iloc는 인덱스 번호로 리리

1000


KeyError: '메로나'

In [41]:
print(s2.iloc[0]) # 0은 위치 0을 의미
print(s2.loc[0])# 0은 라벨 0을 의미 -데이터 프레임할때는 loc로만 기억하면 됨
#둘은 같은 0이지만 전혀 다른값이라고 봐야한다

#필터링 할때는 loc할때 쓰면 됨

1000
1000


# 슬라이싱

In [44]:
s.iloc[0:2]

메로나    1000
월드콘    2000
dtype: int64

In [47]:
s.loc["메로나":"와"] # loc는 직관적

메로나    1000
월드콘    2000
와      3000
dtype: int64

In [48]:
s2.iloc[0:2]

0    1000
1    2000
dtype: int64

In [49]:
s2.loc[0:2]

0    1000
1    2000
2    3000
dtype: int64

## 시리즈 수정/추가/삭제

In [56]:
data = [1000,2000,3000]
index=["메로나","월드콘","와"]
s = pd.Series(data,index)
s

메로나    1000
월드콘    2000
와      3000
dtype: int64

In [60]:
s['메로나']=500
s

메로나     500
월드콘    2000
와      3000
dtype: int64

In [57]:
s.iloc[0]=500
s

메로나     500
월드콘    2000
와      3000
dtype: int64

In [55]:
s.loc['메로나'] = 500 #세가지 중에 이녀석을 추천
s

메로나     500
월드콘    2000
와      3000
dtype: int64

## 시리즈 연산

In [67]:
evan = pd.Series([10,20,30], index=['NAVER','APPLE','엔비디아'])
딸1= pd.Series([10,30,20],index= ["엔비디아","NAVER","APPLE"])

#우리 가족이 보유하고 이는 주식의 숫자를 계산
evan + 딸1

APPLE    40
NAVER    40
엔비디아     40
dtype: int64

In [63]:
딸1

엔비디아     10
NAVER    30
APPLE    20
dtype: int64

In [64]:
evan

NAVER    10
APPLE    20
엔비디아     30
dtype: int64

In [69]:
date = ["6/1", "6/2", "6/3", "6/4", "6/5"]
high = pd.Series([42800, 42700, 42050, 42950, 43000], index=date) #매도
low = pd.Series([42150, 42150, 41300, 42150, 42350] , index=date)#수수

diff =high - low
print(diff)

6/1    650
6/2    550
6/3    750
6/4    800
6/5    650
dtype: int64


In [72]:
# 반복문을 바로 잡을수 있는 메서드
diff.idxmax(),diff[diff.idxmax()]

('6/4', np.int64(800))

In [73]:
diff.idxmin(),diff[diff.idxmin()]

('6/2', np.int64(550))

In [75]:
profit = high/low #단순 수익률 계산
profit

6/1    1.015421
6/2    1.013049
6/3    1.018160
6/4    1.018980
6/5    1.015348
dtype: float64

In [76]:
profit.cumprod() # 누적시키는값

6/1    1.015421
6/2    1.028671
6/3    1.047351
6/4    1.067230
6/5    1.083610
dtype: float64

# 시리즈와 map

In [80]:
text = '1,234'
result = int(text.replace(',',''))
type(result),result

(int, 1234)

In [83]:
num_str = ['1,234', '5,678', '12,345']
results = []
for num in num_str:
    temp = int(num.replace(',',''))
    results.append(temp)

results

[1234, 5678, 12345]

In [87]:
def rm_comma(x):
    return int(x.replace(',',''))

In [88]:
s= pd.Series(['1,234', '5,678', '12,345'])
result = s.map(rm_comma)
result

0     1234
1     5678
2    12345
dtype: int64

In [89]:
def remove_dollar_sign(x):
    return float(x.replace('$', '').replace(',', ''))
s = pd.Series(['$1,234.56', '$5,678.90', '$12,345.67'])
result = s.map(remove_dollar_sign)
result

0     1234.56
1     5678.90
2    12345.67
dtype: float64

# 문제
- 기준 13이상
  + 크다 or 작다

In [94]:
def is_greater_13(x): 

    return_text = None
    if x >= 13:
        return "크다"
    else:
        return "작다" 

s = pd.Series([10, 15, 7, 20, 13])
s.map(is_greater_13)

0    작다
1    크다
2    작다
3    크다
4    크다
dtype: object

In [96]:
result = s.map(lambda x: '크다' if x >=13 else '작다')  # map이나 apply 동일하게 사용가능
result

0    작다
1    크다
2    작다
3    크다
4    크다
dtype: object

In [93]:
s = pd.Series([5, 10, 15, 20])
s = s>=13


0    False
1    False
2     True
3     True
dtype: bool

## 필터링 

In [97]:
data = [42500, 42550, 41800, 42550, 42650]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']
s = pd.Series(data=data, index=index)
s

2019-05-31    42500
2019-05-30    42550
2019-05-29    41800
2019-05-28    42550
2019-05-27    42650
dtype: int64

In [100]:
cond = s > 42000
print(cond)

2019-05-31     True
2019-05-30     True
2019-05-29    False
2019-05-28     True
2019-05-27     True
dtype: bool


In [101]:
s[cond]

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64

In [103]:
s[s> 42000]

2019-05-31    42500
2019-05-30    42550
2019-05-28    42550
2019-05-27    42650
dtype: int64

In [108]:
close = [42500, 42550, 41800, 42550, 42650]
open = [42600, 42200, 41850, 42550, 42500]
index = ['2019-05-31', '2019-05-30', '2019-05-29', '2019-05-28', '2019-05-27']

open = pd.Series(data=open, index=index) #싯가
close = pd.Series(data=close, index=index) #종가

# 종가가 싯가보다 높은 날을 구하세요

close[close>open]

2019-05-30    42550
2019-05-27    42650
dtype: int64